sonar.projectKey=Moeez-Ul-Hassan_Cart_Product
sonar.organization=moeez-ul-hassan

# Tell Sonar where to look for your app code vs your test code
sonar.sources=app
sonar.tests=tests

# Tell Sonar you are using Python
sonar.language=py
sonar.python.version=3.12

# Ignore the virtual environment and logs
sonar.exclusions=venv/**, logs/**, **/__pycache__/**