name: Enterprise CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-scan:
    name: Run Tests & SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Pytest
        run: pytest -v tests/
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push:
    name: Build Docker Image
    needs: test-and-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cart-api:latest

  deploy-green:
    name: Deploy & Flip Traffic
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Green Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_GREEN_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/cart_apps
            sudo docker compose pull api
            sudo docker compose up -d
            # Allow time for the container to start and pass health checks
            sleep 15

      - name: Switch Traffic via Load Balancer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          aws elbv2 modify-listener --listener-arn ${{ secrets.ALB_LISTENER_ARN }} \
          --default-actions Type=forward,TargetGroupArn=${{ secrets.TG_GREEN_ARN }}
          echo "Traffic successfully flipped to Green environment!"